
<html>
<head>
<? echo "<title>GNOME Word of the Day Applet - $pageTitle</title>"; ?>
<link rel="stylesheet" type="text/css" href="styleSheet.css">
</head>

<body>
<div class="header">
<img src="images/header-logo.png"> <img src="images/header-text.png">
</div>
<div class="menu"><a href="index.php">Home</a> | <a href="releases.php">Releases</a> | <a href="screenshots.php">Screenshots</a>
</div>

<div class="content">
